name: Jacoco Report CI

on:
  push:
    branches:
      - add-jacoco

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # run the database
      - name: Start database
        run: |
          docker build -t my-mysql .
          docker run -p 3306:3306 -d my-mysql
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload Jacoco Report
        run: cat target/site/jacoco/jacoco.xml
        
